In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
x=np.arange(15).reshape(-1,1)
y = np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1])
x,y

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1]))

In [ ]:
model = LogisticRegression(C=0.5)
model.fit(x,y)

LogisticRegression(C=0.5)

In [ ]:
model.classes_

array([0, 1])

In [ ]:
model.intercept_


array([-5.96039406])

In [ ]:

model.coef_

array([[0.7944447]])

In [ ]:
model.predict_proba(x)


array([[0.99742774, 0.00257226],
       [0.99432475, 0.00567525],
       [0.98752536, 0.01247464],
       [0.9728026 , 0.0271974 ],
       [0.94172912, 0.05827088],
       [0.87954946, 0.12045054],
       [0.76740677, 0.23259323],
       [0.59851494, 0.40148506],
       [0.40247491, 0.59752509],
       [0.23332901, 0.76667099],
       [0.12088746, 0.87911254],
       [0.05849725, 0.94150275],
       [0.02730655, 0.97269345],
       [0.01252546, 0.98747454],
       [0.00569853, 0.99430147]])

In [ ]:
h=[[5]]
y_pred=model.predict_proba(h)
y_pred

array([[0.87954946, 0.12045054]])

In [ ]:
h=[[5]]
y_pred=model.predict(h)
print("probability of selection",y_pred)


probability of selection [0]


In [ ]:
model.score(x,y)

0.8666666666666667

In [ ]:
model = LogisticRegression(C=0.1)
model.fit(x,y)

LogisticRegression(C=0.1)

In [ ]:
model.predict_proba(x)


array([[0.9756072 , 0.0243928 ],
       [0.9607829 , 0.0392171 ],
       [0.9375263 , 0.0624737 ],
       [0.9018864 , 0.0981136 ],
       [0.84918538, 0.15081462],
       [0.77523132, 0.22476868],
       [0.67873255, 0.32126745],
       [0.56409952, 0.43590048],
       [0.44217989, 0.55782011],
       [0.32685234, 0.67314766],
       [0.22924263, 0.77075737],
       [0.15410916, 0.84589084],
       [0.10039299, 0.89960701],
       [0.06398385, 0.93601615],
       [0.04018917, 0.95981083]])

In [ ]:
model.predict(x)


array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
h=[[10],[4]]
y_pred=model.predict(h)
print("probability of selection",y_pred)


probability of selection [1 0]


In [ ]:
h=[[4.5],[8.4]]
y_pred=model.predict(h)
print("probability of selection",y_pred)

probability of selection [0 1]


#**Logistic Regression for handwriting recognition**

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [7]:
X,y=load_digits(return_X_y=True)


In [10]:
X.shape,y.shape

((1797, 64), (1797,))